### PR TITLE
WEBAPP-164 add leverage input

### PR DESCRIPTION
**Pull request by doylio**
## Changelog
- Replace leverage slider checkbox with input
- Refactor leverage inputs into single component

### CODE REVIEW

**Comment by rogue-hacker** [comment]
Do you think that the leverage box length is a bit too long:

image

Could be 60px as the 30.5x leverage is the max amount that could be entered. Also possibly validate input and prevent numbers larger than 30.5 from being entered (I could enter 10000+):

image

Could also be good to make the font in the input box bold to match the other input styles (and possibly center align text)

Looks and works great otherwise

**Comment by doylio** [comment]
@rogue-hacker 

I've reduced the width to 60px

Input validation is done on the `onBlur` event.  So you can enter whatever number you want, but it won't take effect until you press Enter, Tab or click away.  At that point, any values about or below the accepted range and rounded to the max or min

**Comment by rogue-hacker** [comment]
Changes look good. Though I get a client-side error which crashes the page after typing in a value to the leverage input, it saving the input (e.g. 30.5), then connecting wallet 

image

**Review by rogue-hacker — CHANGES_REQUESTED** [review]
Resolve client side error as above

**Review by rogue-hacker — APPROVED** [review]

**Review by dospore — APPROVED** [review]

**Comment by dospore** [comment]
@rogue-hacker @doylio kurtis wanted some design changes to this, not sure where the ticket came from but is not our fault so just waiting on him to sort that out with designers

**Review by dospore — CHANGES_REQUESTED** [review]
Code lgtm, but design changes request from Kurtis

**Pull request merged**
